mod new_project;
mod project_address;
mod project_banner;
mod project_category_id;
mod project_description;
mod project_email;
mod project_facebook;
mod project_instagram;
mod project_linkedin;
mod project_modality;
mod project_name;
mod project_picture;
mod project_professor;
mod project_timestamp;
mod project_twitter;
mod project_website;
pub use new_project::NewProject;
pub use project_address::ProjectAddress;
pub use project_banner::ProjectBanner;
pub use project_category_id::ProjectCategoryId;
pub use project_description::ProjectDescription;
pub use project_email::ProjectEmail;
pub use project_facebook::ProjectFacebook;
pub use project_instagram::ProjectInstagram;
pub use project_linkedin::ProjectLinkedin;
pub use project_modality::ProjectModality;
pub use project_name::ProjectName;
pub use project_picture::ProjectPicture;
pub use project_professor::ProjectProfessor;
pub use project_timestamp::ProjectTimestamp;
pub use project_twitter::ProjectTwitter;
pub use project_website::ProjectWebsite;
